name: KitPVP
version: 2.69
main: kitpvp.Kitpvp

commands:
  kitpvp:
    description: Spawns Kit
  gamemaster:
    description: Changes into Gamemaster
  ratchet:
    description: Plays a particle effect


##author: CAmadeusA
##license: CreativecommonsLCC